CREATE TABLE IF NOT EXISTS "take-home-fullstack_github_users" (
	"id" serial PRIMARY KEY NOT NULL,
	"github_id" varchar(256),
	"username" varchar(256),
	"avatar_url" varchar(256),
	"url" varchar(256),
	"html_url" varchar(256),
	"followers_url" varchar(256),
	"following_url" varchar(256),
	"gists_url" varchar(256),
	"starred_url" varchar(256),
	"subscriptions_url" varchar(256),
	"organizations_url" varchar(256),
	"repos_url" varchar(256),
	"events_url" varchar(256),
	"received_events_url" varchar(256),
	"type" varchar(256),
	"site_admin" boolean,
	"name" varchar(256),
	"company" varchar(256),
	"blog" varchar(256),
	"location" varchar(256),
	"email" varchar(256),
	"hireable" boolean,
	"bio" varchar(256),
	"twitter_username" varchar(256),
	"public_repos" integer,
	"public_gists" integer,
	"followers" integer,
	"following" integer,
	"registration_date" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "take-home-fullstack_github_users_github_id_unique" UNIQUE("github_id"),
	CONSTRAINT "take-home-fullstack_github_users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "github_id_idx" ON "take-home-fullstack_github_users" ("github_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "username_idx" ON "take-home-fullstack_github_users" ("username");