import Head from "next/head";

import { api } from "~/utils/api";

export default function Home() {
  const latestGithubUser = api.githubUsers.getLatest.useQuery(); // api.post.getLatest.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h2>Latest User</h2>
          {latestGithubUser.data && (
            <div>
              {Object.entries(latestGithubUser.data).map(([key, value]) => (
                <p key={key}>
                  <span className="font-bold">{key}:</span>{" "}
                  <span>
                    {value?.toString() ?? (
                      <span className="text-red-600">N/A</span>
                    )}
                  </span>
                </p>
              ))}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
